version: '3.8'

services:
  user_management:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mysql+pymysql://root:Space7050@host.docker.internal:3306/user_db
