version: "3.9"

services:
  quotationservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quotationservice
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./.env:/app/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Important for Linux, safe for others too
