version: '3.8'

services:
  policy_management:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=mysql+pymysql://root:Space7050@host.docker.internal:3306/policy_db
